# -*- coding: utf-8 -*-
"""datacleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0FsZP21plbfindZKmeBXKFbxPAVlckf
"""

import pandas as pd

medicine = pd.read_csv('/content/drive/MyDrive/Komal varma/medicine_dataset.csv')

columns_to_keep = ['medicine', 'substitute0', 'substitute1', 'substitute2', 'substitute3', 'substitute4','use0', 'use1', 'use2', 'use3','use4', 'Therapeutic Class',]
medicine = medicine[columns_to_keep]
medicine.fillna(' ', inplace=True)
medicine.head(10)

# Step 2: Combine the 'use1' to 'use5' columns into a single column 'uses'
medicine['uses'] = medicine[['use0', 'use1', 'use3', 'use2', 'use4']].apply(lambda row: ', '.join(row.dropna().astype(str)), axis=1)

# Step 3: Drop the 'use1' to 'use5' columns
medicine.drop(['use1', 'use2', 'use3', 'use4', 'use0'], axis=1, inplace=True)



medicine.head()
destination_path = '/content/drive/MyDrive/Komal varma/medicinedata.csv'
medicine.to_csv(destination_path, index=False)

df = pd.read_csv('/content/drive/MyDrive/Komal varma/medicinedata.csv')

df.head()

df['substitutes'] = df[['substitute0', 'substitute1', 'substitute2', 'substitute3', 'substitute4']].apply(lambda row: ', '.join(row.dropna().astype(str)), axis=1)

# Step 3: Drop the 'use1' to 'use5' columns
df.drop(['substitute0', 'substitute1', 'substitute2', 'substitute3', 'substitute4'], axis=1, inplace=True)

df.head()
print(df.iloc[5])
print(df)

df.head()
destination_path = '/content/drive/MyDrive/Komal varma/medicinedataset.csv'
df.to_csv(destination_path, index=False)

